services:
  - type: worker
    name: social-posts-worker
    env: node
    plan: starter
    buildCommand: npm install && npm run build
    startCommand: npm run worker
    envVars:
      - key: REDIS_URL
        sync: false
      - key: TWITTER_CLIENT_ID
        sync: false
      - key: TWITTER_CLIENT_SECRET
        sync: false
      - key: TWITTER_CALLBACK_URL
        sync: false
      - key: TWITTER_STATE
        sync: false
      - key: LINKEDIN_CLIENT_ID
        sync: false
      - key: LINKEDIN_CLIENT_SECRET
        sync: false
      - key: LINKEDIN_CALLBACK_URL
        sync: false
