// import type { Post } from '@/components/posts/types';

// // Temporary mock data for development
// export const MOCK_POSTS: Post[] = [
//   {
//     id: '1',
//     userId: 'user-1',
//     organizationId: null,
//     status: 'SCHEDULED',
//     reviewStatus: 'PENDING',
//     privacyStatus: 'PUBLIC',
//     postFailureReason: null,
//     scheduledAt: new Date('2024-04-01'),
//     publishedAt: null,
//     lastFailedAt: null,
//     retryCount: 0,
//     isDeleted: false,
//     platformPosts: [
//       {
//         id: 'pp-1',
//         platformId: 'sp-1',
//         platformPostUrl: 'https://twitter.com/twitteruser/status/1234567890',
//         platformPostId: 'sp-1',
//       },
//     ],
//     content: [
//       {
//         text: 'Excited to announce our latest product launch! 🚀 Stay tuned for more updates. #innovation #tech',
//         media: [
//           {
//             url: 'https://picsum.photos/800/600',
//             mediaType: 'IMAGE',
//             altText: 'Product launch image',
//           },
//           {
//             url: 'https://picsum.photos/800/601',
//             mediaType: 'IMAGE',
//             altText: 'Product features',
//           },
//         ],
//         name: 'Product launch',
//         order: 0,
//         tags: ['innovation', 'tech'],
//       },
//     ],
//     socialProviders: [
//       {
//         id: 'sp-1',
//         accessToken: 'token',
//         refreshToken: null,
//         expiresIn: new Date('2024-12-31'),
//         refreshTokenExpiresIn: null,
//         profileId: 'twitter-1',
//         username: 'twitteruser',
//         fullName: 'Twitter User',
//         profileImage: '',
//         socialType: 'TWITTER',
//         isActive: true,
//         lastSyncedAt: null,
//       },
//       {
//         id: 'sp-2',
//         userId: 'user-1',
//         clientId: null,
//         clientSecret: null,
//         accessToken: 'token',
//         refreshToken: null,
//         expiresIn: new Date('2024-12-31'),
//         refreshTokenExpiresIn: null,
//         profileId: 'instagram-1',
//         username: 'instagramuser',
//         fullName: 'Instagram User',
//         profileImage: '',
//         socialType: 'INSTAGRAM',
//         isActive: true,
//         lastSyncedAt: null,
//         createdAt: new Date(),
//         updatedAt: new Date(),
//       },
//       {
//         id: 'sp-3',
//         organizationId: null,
//         userId: 'user-1',
//         clientId: null,
//         clientSecret: null,
//         accessToken: 'token',
//         refreshToken: null,
//         expiresIn: new Date('2024-12-31'),
//         refreshTokenExpiresIn: null,
//         profileId: 'linkedin-1',
//         username: 'linkedinuser',
//         fullName: 'LinkedIn User',
//         profileImage: '',
//         socialType: 'LINKEDIN',
//         isActive: false,
//         lastSyncedAt: null,
//         createdAt: new Date(),
//         updatedAt: new Date(),
//       },
//     ],
//   },
//   {
//     id: '2',
//     userId: 'user-1',
//     organizationId: null,
//     status: 'PUBLISHED',
//     reviewStatus: 'APPROVED',
//     privacyStatus: 'PUBLIC',
//     postFailureReason: null,
//     scheduledAt: new Date('2024-03-15'),
//     publishedAt: new Date('2024-03-15'),
//     lastFailedAt: null,
//     retryCount: 0,
//     isDeleted: false,
//     content: [
//       {
//         text: 'Just wrapped up an amazing conference! 🎯 Great insights on AI and machine learning. Thanks to all attendees! #AIConference #TechTalks',
//         media: [
//           {
//             url: 'https://picsum.photos/800/602',
//             mediaType: 'IMAGE',
//             altText: 'Conference keynote',
//           },
//         ],
//         name: 'Conference recap',
//         order: 0,
//         tags: ['conference', 'AI', 'tech'],
//       },
//     ],
//     socialProviders: [
//       {
//         id: 'sp-4',
//         organizationId: null,
//         userId: 'user-1',
//         clientId: null,
//         clientSecret: null,
//         accessToken: 'token',
//         refreshToken: null,
//         expiresIn: new Date('2024-12-31'),
//         refreshTokenExpiresIn: null,
//         profileId: 'twitter-1',
//         username: 'twitteruser',
//         fullName: 'Twitter User',
//         profileImage: '',
//         socialType: 'TWITTER',
//         isActive: true,
//         lastSyncedAt: null,
//         createdAt: new Date(),
//         updatedAt: new Date(),
//       },
//     ],
//   },
//   {
//     id: '3',
//     userId: 'user-1',
//     organizationId: null,
//     status: 'SAVED',
//     reviewStatus: 'PENDING',
//     privacyStatus: 'PUBLIC',
//     postFailureReason: null,
//     scheduledAt: null,
//     publishedAt: null,
//     lastFailedAt: null,
//     retryCount: 0,
//     isDeleted: false,
//     content: [
//       {
//         text: "Working on something exciting! 🎨 Can't wait to share our new design system with the community. #Design #UX",
//         media: [],
//         name: 'Design teaser',
//         order: 0,
//         tags: ['design', 'UX'],
//       },
//     ],
//     socialProviders: [
//       {
//         id: 'sp-5',
//         organizationId: null,
//         userId: 'user-1',
//         clientId: null,
//         clientSecret: null,
//         accessToken: 'token',
//         refreshToken: null,
//         expiresIn: new Date('2024-12-31'),
//         refreshTokenExpiresIn: null,
//         profileId: 'linkedin-1',
//         username: 'linkedinuser',
//         fullName: 'LinkedIn User',
//         profileImage: '',
//         socialType: 'LINKEDIN',
//         isActive: true,
//         lastSyncedAt: null,
//         connected: true,
//       },
//     ],
//   },
//   {
//     id: '4',
//     userId: 'user-1',
//     organizationId: null,
//     status: 'FAILED',
//     reviewStatus: 'APPROVED',
//     privacyStatus: 'PUBLIC',
//     postFailureReason: 'API rate limit exceeded',
//     scheduledAt: new Date('2024-03-10'),
//     publishedAt: null,
//     lastFailedAt: new Date('2024-03-10'),
//     retryCount: 3,
//     isDeleted: false,
//     content: [
//       {
//         text: 'Check out our latest blog post on web performance optimization! 🚀 Link in bio. #WebDev #Performance',
//         media: [
//           {
//             url: 'https://picsum.photos/800/603',
//             mediaType: 'IMAGE',
//             altText: 'Blog post cover',
//           },
//         ],
//         name: 'Blog promotion',
//         order: 0,
//         tags: ['webdev', 'performance'],
//       },
//     ],
//     socialProviders: [
//       {
//         id: 'sp-6',
//         organizationId: null,
//         userId: 'user-1',
//         clientId: null,
//         clientSecret: null,
//         accessToken: 'token',
//         refreshToken: null,
//         expiresIn: new Date('2024-12-31'),
//         refreshTokenExpiresIn: null,
//         profileId: 'instagram-1',
//         username: 'instagramuser',
//         fullName: 'Instagram User',
//         profileImage: '',
//         socialType: 'INSTAGRAM',
//         isActive: true,
//         lastSyncedAt: null,
//         connected: true,
//       },
//     ],
//   },
//   {
//     id: '5',
//     userId: 'user-1',
//     organizationId: null,
//     status: 'SCHEDULED',
//     reviewStatus: 'PENDING',
//     privacyStatus: 'PUBLIC',
//     postFailureReason: null,
//     scheduledAt: new Date('2024-04-05'),
//     publishedAt: null,
//     lastFailedAt: null,
//     retryCount: 0,
//     isDeleted: false,
//     content: [
//       {
//         text: 'Join us for our monthly community meetup! 🤝 Virtual and in-person options available. RSVP now! #Community #Networking',
//         media: [
//           {
//             url: 'https://picsum.photos/800/604',
//             mediaType: 'IMAGE',
//             altText: 'Meetup banner',
//           },
//         ],
//         name: 'Meetup announcement',
//         order: 0,
//         tags: ['community', 'networking'],
//       },
//     ],
//     socialProviders: [
//       {
//         id: 'sp-7',
//         organizationId: null,
//         userId: 'user-1',
//         clientId: null,
//         clientSecret: null,
//         accessToken: 'token',
//         refreshToken: null,
//         expiresIn: new Date('2024-12-31'),
//         refreshTokenExpiresIn: null,
//         profileId: 'twitter-1',
//         username: 'twitteruser',
//         fullName: 'Twitter User',
//         profileImage: '',
//         socialType: 'TWITTER',
//         isActive: true,
//         lastSyncedAt: null,
//         connected: true,
//       },
//       {
//         id: 'sp-8',
//         organizationId: null,
//         userId: 'user-1',
//         clientId: null,
//         clientSecret: null,
//         accessToken: 'token',
//         refreshToken: null,
//         expiresIn: new Date('2024-12-31'),
//         refreshTokenExpiresIn: null,
//         profileId: 'linkedin-1',
//         username: 'linkedinuser',
//         fullName: 'LinkedIn User',
//         profileImage: '',
//         socialType: 'LINKEDIN',
//         isActive: true,
//         lastSyncedAt: null,
//         connected: true,
//       },
//     ],
//   },
//   {
//     id: '6',
//     userId: 'user-1',
//     organizationId: null,
//     status: 'PUBLISHED',
//     reviewStatus: 'APPROVED',
//     privacyStatus: 'PUBLIC',
//     postFailureReason: null,
//     scheduledAt: new Date('2024-03-01'),
//     publishedAt: new Date('2024-03-01'),
//     lastFailedAt: null,
//     retryCount: 0,
//     isDeleted: false,
//     content: [
//       {
//         text: "We're hiring! 🎉 Looking for talented developers to join our growing team. #JobOpening #TechJobs",
//         media: [
//           {
//             url: 'https://picsum.photos/800/605',
//             mediaType: 'IMAGE',
//             altText: 'Job posting image',
//           },
//         ],
//         name: 'Job posting',
//         order: 0,
//         tags: ['hiring', 'jobs'],
//       },
//     ],
//     socialProviders: [
//       {
//         id: 'sp-9',
//         organizationId: null,
//         userId: 'user-1',
//         clientId: null,
//         clientSecret: null,
//         accessToken: 'token',
//         refreshToken: null,
//         expiresIn: new Date('2024-12-31'),
//         refreshTokenExpiresIn: null,
//         profileId: 'linkedin-1',
//         username: 'linkedinuser',
//         fullName: 'LinkedIn User',
//         profileImage: '',
//         socialType: 'LINKEDIN',
//         isActive: true,
//         lastSyncedAt: null,
//         connected: true,
//       },
//     ],
//   },
//   {
//     id: '7',
//     userId: 'user-1',
//     organizationId: null,
//     status: 'SCHEDULED',
//     reviewStatus: 'PENDING',
//     privacyStatus: 'PUBLIC',
//     postFailureReason: null,
//     scheduledAt: new Date('2024-04-10'),
//     publishedAt: null,
//     lastFailedAt: null,
//     retryCount: 0,
//     isDeleted: false,
//     content: [
//       {
//         text: '📱 Our mobile app just got a major update! New features include dark mode, improved performance, and more! #MobileApp #ProductUpdate',
//         media: [
//           {
//             url: 'https://picsum.photos/800/606',
//             mediaType: 'IMAGE',
//             altText: 'App update features',
//           },
//           {
//             url: 'https://picsum.photos/800/607',
//             mediaType: 'IMAGE',
//             altText: 'Dark mode preview',
//           },
//         ],
//         name: 'App update',
//         order: 0,
//         tags: ['mobile', 'update'],
//       },
//     ],
//     socialProviders: [
//       {
//         id: 'sp-10',
//         organizationId: null,
//         userId: 'user-1',
//         clientId: null,
//         clientSecret: null,
//         accessToken: 'token',
//         refreshToken: null,
//         expiresIn: new Date('2024-12-31'),
//         refreshTokenExpiresIn: null,
//         profileId: 'twitter-1',
//         username: 'twitteruser',
//         fullName: 'Twitter User',
//         profileImage: '',
//         socialType: 'TWITTER',
//         isActive: true,
//         lastSyncedAt: null,
//         connected: true,
//       },
//       {
//         id: 'sp-11',
//         organizationId: null,
//         userId: 'user-1',
//         clientId: null,
//         clientSecret: null,
//         accessToken: 'token',
//         refreshToken: null,
//         expiresIn: new Date('2024-12-31'),
//         refreshTokenExpiresIn: null,
//         profileId: 'instagram-1',
//         username: 'instagramuser',
//         fullName: 'Instagram User',
//         profileImage: '',
//         socialType: 'INSTAGRAM',
//         isActive: true,
//         lastSyncedAt: null,
//         connected: true,
//       },
//     ],
//   },
//   {
//     id: '8',
//     userId: 'user-1',
//     organizationId: null,
//     status: 'SAVED',
//     reviewStatus: 'PENDING',
//     privacyStatus: 'PUBLIC',
//     postFailureReason: null,
//     scheduledAt: null,
//     publishedAt: null,
//     lastFailedAt: null,
//     retryCount: 0,
//     isDeleted: false,
//     content: [
//       {
//         text: '🎓 Proud to announce our new developer education program! Free workshops starting next month. #Education #CodingBootcamp',
//         media: [],
//         name: 'Education program',
//         order: 0,
//         tags: ['education', 'coding'],
//       },
//     ],
//     socialProviders: [
//       {
//         id: 'sp-12',
//         organizationId: null,
//         userId: 'user-1',
//         clientId: null,
//         clientSecret: null,
//         accessToken: 'token',
//         refreshToken: null,
//         expiresIn: new Date('2024-12-31'),
//         refreshTokenExpiresIn: null,
//         profileId: 'linkedin-1',
//         username: 'linkedinuser',
//         fullName: 'LinkedIn User',
//         profileImage: '',
//         socialType: 'LINKEDIN',
//         isActive: true,
//         lastSyncedAt: null,
//         connected: true,
//       },
//     ],
//   },
//   {
//     id: '9',
//     userId: 'user-1',
//     organizationId: null,
//     status: 'PUBLISHED',
//     reviewStatus: 'APPROVED',
//     privacyStatus: 'PUBLIC',
//     postFailureReason: null,
//     scheduledAt: new Date('2024-03-20'),
//     publishedAt: new Date('2024-03-20'),
//     lastFailedAt: null,
//     retryCount: 0,
//     isDeleted: false,
//     content: [
//       {
//         text: '🏆 Honored to be named one of the top startups to watch in 2024! Thank you to our amazing team and customers. #StartupLife #Achievement',
//         media: [
//           {
//             url: 'https://picsum.photos/800/608',
//             mediaType: 'IMAGE',
//             altText: 'Award ceremony',
//           },
//         ],
//         name: 'Award announcement',
//         order: 0,
//         tags: ['startup', 'awards'],
//       },
//     ],
//     socialProviders: [
//       {
//         id: 'sp-13',
//         organizationId: null,
//         userId: 'user-1',
//         clientId: null,
//         clientSecret: null,
//         accessToken: 'token',
//         refreshToken: null,
//         expiresIn: new Date('2024-12-31'),
//         refreshTokenExpiresIn: null,
//         profileId: 'twitter-1',
//         username: 'twitteruser',
//         fullName: 'Twitter User',
//         profileImage: '',
//         socialType: 'TWITTER',
//         isActive: true,
//         lastSyncedAt: null,
//         connected: true,
//       },
//       {
//         id: 'sp-14',
//         organizationId: null,
//         userId: 'user-1',
//         clientId: null,
//         clientSecret: null,
//         accessToken: 'token',
//         refreshToken: null,
//         expiresIn: new Date('2024-12-31'),
//         refreshTokenExpiresIn: null,
//         profileId: 'linkedin-1',
//         username: 'linkedinuser',
//         fullName: 'LinkedIn User',
//         profileImage: '',
//         socialType: 'LINKEDIN',
//         isActive: true,
//         lastSyncedAt: null,
//         connected: true,
//       },
//     ],
//   },
//   {
//     id: '10',
//     userId: 'user-1',
//     organizationId: null,
//     status: 'SCHEDULED',
//     reviewStatus: 'PENDING',
//     privacyStatus: 'PUBLIC',
//     postFailureReason: null,
//     scheduledAt: new Date('2024-04-15'),
//     publishedAt: null,
//     lastFailedAt: null,
//     retryCount: 0,
//     isDeleted: false,
//     content: [
//       {
//         text: '💡 New blog post: "10 Tips for Building Scalable Microservices" - Check it out on our website! #Microservices #Architecture',
//         media: [
//           {
//             url: 'https://picsum.photos/800/609',
//             mediaType: 'IMAGE',
//             altText: 'Blog post thumbnail',
//           },
//         ],
//         name: 'Blog post promotion',
//         order: 0,
//         tags: ['blog', 'microservices'],
//       },
//     ],
//     socialProviders: [
//       {
//         id: 'sp-15',
//         organizationId: null,
//         userId: 'user-1',
//         clientId: null,
//         clientSecret: null,
//         accessToken: 'token',
//         refreshToken: null,
//         expiresIn: new Date('2024-12-31'),
//         refreshTokenExpiresIn: null,
//         profileId: 'twitter-1',
//         username: 'twitteruser',
//         fullName: 'Twitter User',
//         profileImage: '',
//         socialType: 'TWITTER',
//         isActive: true,
//         lastSyncedAt: null,
//         connected: true,
//       },
//     ],
//   },
// ];
