/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

declare module "sst" {
  export interface Resource {
    "CONVEX_URL": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "INSTAGRAM_APP_SECRET": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "INSTAGRAM_WEBHOOK_VERIFY_TOKEN": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "InstagramWebhook": {
      "name": string
      "type": "sst.aws.Function"
      "url": string
    }
    "LAMBDA_SECRET_KEY": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "SocialPostsQueue": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "TriggerSqsFunction": {
      "name": string
      "type": "sst.aws.Function"
      "url": string
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}