export const keys = () => ({
  TWITTER_CLIENT_SECRET: process.env.TWITTER_CLIENT_SECRET || "",
  TWITTER_CLIENT_ID: process.env.TWITTER_CLIENT_ID || "",
  TWITTER_CALLBACK_URL: process.env.TWITTER_CALLBACK_URL || "",
  TWITTER_STATE: process.env.TWITTER_STATE || "",

  LINKEDIN_CLIENT_ID: process.env.LINKEDIN_CLIENT_ID || "",
  LINKEDIN_CLIENT_SECRET: process.env.LINKEDIN_CLIENT_SECRET || "",
  LINKEDIN_CALLBACK_URL: process.env.LINKEDIN_CALLBACK_URL || "",

  INSTAGRAM_CLIENT_ID: process.env.INSTAGRAM_CLIENT_ID || "",
  INSTAGRAM_CLIENT_SECRET: process.env.INSTAGRAM_CLIENT_SECRET || "",
  INSTAGRAM_CALLBACK_URL: process.env.INSTAGRAM_CALLBACK_URL || "",

  THREADS_CLIENT_ID: process.env.THREADS_CLIENT_ID || "",
  THREADS_CLIENT_SECRET: process.env.THREADS_CLIENT_SECRET || "",
  THREADS_CALLBACK_URL: process.env.THREADS_CALLBACK_URL || "",

  FACEBOOK_CLIENT_ID: process.env.FACEBOOK_CLIENT_ID || "",
  FACEBOOK_CLIENT_SECRET: process.env.FACEBOOK_CLIENT_SECRET || "",
  FACEBOOK_CALLBACK_URL: process.env.FACEBOOK_CALLBACK_URL || "",

  PINTEREST_CLIENT_ID: process.env.PINTEREST_CLIENT_ID || "",
  PINTEREST_CLIENT_SECRET: process.env.PINTEREST_CLIENT_SECRET || "",
  PINTEREST_CALLBACK_URL: process.env.PINTEREST_CALLBACK_URL || "",

  GOOGLE_CLIENT_ID: process.env.GOOGLE_CLIENT_ID || "",
  GOOGLE_CLIENT_SECRET: process.env.GOOGLE_CLIENT_SECRET || "",
  YOUTUBE_CALLBACK_URL: process.env.YOUTUBE_CALLBACK_URL || "",

  TIKTOK_CLIENT_ID: process.env.TIKTOK_CLIENT_ID || "",
  TIKTOK_CLIENT_SECRET: process.env.TIKTOK_CLIENT_SECRET || "",
  TIKTOK_CALLBACK_URL: process.env.TIKTOK_CALLBACK_URL || "",

  FARCASTER_APP_FID: process.env.FARCASTER_APP_FID || "",
  FARCASTER_MNEMONIC: process.env.FARCASTER_MNEMONIC || "",

  REDIS_URL: process.env.REDIS_URL || "",
});
